"""
Django settings for first_project project.

Generated by '3.django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bsok4=7c%m0toi-5s^3(l(7*(#&-mrxcbvfxmmh#_v82qfiylb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    '3.django.contrib.admin',
    '3.django.contrib.auth',
    '3.django.contrib.contenttypes',
    '3.django.contrib.sessions',
    '3.django.contrib.messages',
    '3.django.contrib.staticfiles',

    # здесь мы подключаем наши приложения
    'app'
]

MIDDLEWARE = [
    '3.django.middleware.security.SecurityMiddleware',
    '3.django.contrib.sessions.middleware.SessionMiddleware',
    '3.django.middleware.common.CommonMiddleware',
    '3.django.middleware.csrf.CsrfViewMiddleware',
    '3.django.contrib.auth.middleware.AuthenticationMiddleware',
    '3.django.contrib.messages.middleware.MessageMiddleware',
    '3.django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'first_project.urls'

TEMPLATES = [
    {
        'BACKEND': '3.django.template.backends.3.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                '3.django.template.context_processors.debug',
                '3.django.template.context_processors.request',
                '3.django.contrib.auth.context_processors.auth',
                '3.django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'first_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': '3.django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': '3.django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': '3.django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': '3.django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': '3.django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
