# Generated by Django 2.2.7 on 2019-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190811_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(default=1, max_length=2000, verbose_name='Характеристики'),
            preserve_default=False,
        ),
    ]
